spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: mycssg1314
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: itcast
    password: 123321
    host: 8.130.17.7
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 8.130.17.7
    database: 0
    port: 6379
    password:
  cache:
    cache-names: menus_cache

server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://8.130.17.7/